In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
y= np.array([2,4,5,4,5])

In [3]:
x.shape

(5,)

In [4]:
y.shape

(5,)

In [5]:
X_mean = np.mean(x)  # X Bar
X_mean

3.0

In [6]:
y_mean = np.mean(y)

In [7]:
y_mean

4.0

In [8]:
X_minu_X_bar  = x-X_mean
X_minu_X_bar

array([-2., -1.,  0.,  1.,  2.])

In [9]:
Y_minu_Y_bar = y-y_mean
Y_minu_Y_bar

array([-2.,  0.,  1.,  0.,  1.])

In [10]:
X_minu_X_bar_square = X_minu_X_bar**2
X_minu_X_bar_square

array([4., 1., 0., 1., 4.])

In [11]:
sum_of_X_minu_X_bar_square = np.sum(X_minu_X_bar_square)
sum_of_X_minu_X_bar_square

10.0

In [12]:
X_minu_X_bar_Y_minu_Y_bar = (X_minu_X_bar)*(Y_minu_Y_bar)
X_minu_X_bar_Y_minu_Y_bar

array([ 4., -0.,  0.,  0.,  2.])

In [13]:
sum_X_minu_X_bar_Y_minu_Y_bar = np.sum(X_minu_X_bar_Y_minu_Y_bar)
sum_X_minu_X_bar_Y_minu_Y_bar

6.0

In [14]:
beta_1 = sum_X_minu_X_bar_Y_minu_Y_bar / sum_of_X_minu_X_bar_square
beta_1

0.6

In [15]:
beta_0 = y_mean - beta_1*(X_mean)
beta_0

2.2

In [16]:
X_new = 10

In [17]:
Y_hat = beta_0 + beta_1*(X_new)
Y_hat

8.2

In [18]:
def linear(feature,target,x_new):
    x =feature 
    y= target
    X_mean = np.mean(x)  # X Bar
    y_mean = np.mean(y)
    X_minu_X_bar  = x-X_mean
    Y_minu_Y_bar = y-y_mean
    X_minu_X_bar_square = X_minu_X_bar**2
    sum_of_X_minu_X_bar_square = np.sum(X_minu_X_bar_square)
    X_minu_X_bar_Y_minu_Y_bar = (X_minu_X_bar)*(Y_minu_Y_bar)
    sum_X_minu_X_bar_Y_minu_Y_bar = np.sum(X_minu_X_bar_Y_minu_Y_bar)
    beta_1 = sum_X_minu_X_bar_Y_minu_Y_bar / sum_of_X_minu_X_bar_square
    beta_0 = y_mean - beta_1*(X_mean)
    Y_hat = beta_0 + beta_1*(X_new)
    return {'beta_0':beta_0,'beta_1':beta_1,'predication':Y_hat,'x':x_new}

In [19]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,5,4,5])

In [20]:
X_new = 55

In [21]:
linear(feature=x,target=y,x_new= X_new)

{'beta_0': 2.2, 'beta_1': 0.6, 'predication': 35.2, 'x': 55}